[[opentsdb]]
name = "opentsdb-tcp"
bind-addr = "127.0.0.1:9096"
output = [
    { name="influxdb-01", location="10.111.101.129:14242", initConns=10, maxConns=30, timeout="50s", },
    { name="influxdb-02", location="10.111.75.172:14242", initConns=10, maxConns=30, timeout="50s", },
]