[[opentsdb]]
name = "opentsdb-tcp"
bind-addr = "127.0.0.1:9096"
output = [
    { name="influxdb-24242", location="127.0.0.1:24242", initCap=2, maxCap=30, idleTimeout="60m"},
    { name="influxdb-14242", location="127.0.0.1:14242", initCap=2, maxCap=30, idleTimeout="60m"},
]