[[opentsdb]]
name = "opentsdb-tcp"
bind-addr = "127.0.0.1:9096"
output = [
    { name="influxdb-01", location="127.0.0.1:24242", initCap=10, maxCap=30, idleTimeout="60s"},
    { name="influxdb-02", location="127.0.0.1:14242", initCap=10, maxCap=30, idleTimeout="60s"},
]